name: zenscape_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  get: ^4.6.5
  http: ^0.13.4
  json_annotation: ^4.4.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.0.3
  toggle_switch: ^2.0.1
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  persistent_bottom_nav_bar: 5.0.2
  provider: ^6.0.5
  simple_rich_text: ^2.0.49
  new_version: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  image_path: 'assets/images/zenscapeLogo.png'
  android: true
  ios: true

  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_native_splash: ^2.1.6
flutter_native_splash:
  color: '#D9F4FF'
  image: 'assets/images/zenscapeLogo.png'

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/zenscape_logos/
    - assets/images/banner_logos/
    - assets/svgfiles/
    - assets/ca/
    - assets/jsonFiles/
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf


    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
